name: GitHub Webhook Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  webhook-test:
    name: Webhook Test Job Sample 4
    runs-on: ubuntu-latest

    steps:
      - name: Start Test
        invalid-property : test
        run: |
          echo "GitHub Actions webhook test started"
          echo "Runner: $RUNNER_NAME"

      - name: Wait for webhook events
        run: |
          echo "Sleeping for 20 seconds..."
          sleep 20

      - name: Complete Test
        run: |
          echo "GitHub Actions webhook test completed"