name: VMSS Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, azure-vmss]

    steps:
      - name: Test runner
        run: |
          echo "VMSS runner started"
          hostname
          sleep 30